### ISSUE TITLE
Генерация темы

### ISSUE THREAD

**Issue by Nelfimov** [atls/team-management#1]
### С чем связан запрос на фичу?

Необходимо собрать тему из дизайна.

### Расскажите как вы это себе видите

- [x] используем генератор https://github.com/atls/figma
- [x] тему собираем в `ui` слое
- [x] проверяем полученные данные на наличие "лишнего"

### Definition of done (критерий готовности)

Тема собрана, соответствует дизайну, находится в `ui` слое.

### Приложите пример реализаций

https://github.com/torin-asakura/drum-in/tree/master/ui/theme
https://github.com/torin-asakura/dream-team/tree/master/ui/theme
https://github.com/torin-asakura/drum-in/blob/910c70a202cce0dee5fd760430994bc8b7d9d3b9/ui/button/package.json#L6

### Приложите материалы задачи

https://www.figma.com/file/2vNHefkDcMKAFSnw69RbMM/Team-management-system?type=design&node-id=0-1&mode=design&t=Xbq1nSce06sKbif8-11

**Comment by effektivnayarabota1** [comment]
запускаю скрипт `yarn dlx @atls/figma-theme-cli generate-theme 2vNHefkDcMKAFSnw69RbMM`, возвращает ошибку: 

нормально запускался, когда устанавливал этот пакет прямо в приложение, сейчас и так не работает.
после копии репозитории качаю пакеты `yarn install`

```
/tmp/xfs-22cbb318/dlx-22616/.pnp.cjs:6186
    throw firstError;
    ^

Error: @atls/figma-theme-font-sizes-generator tried to access @atls/figma-theme-generator-common (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: @atls/figma-theme-generator-common
Required by: @atls/figma-theme-font-sizes-generator@virtual:7d78111ddc485c407ed15730693c74868e47409ff22aed66180d37955ab733862d7f4d8d249e08c791a798eca5224c903df3b565795147b6c3a79f050da4616c#npm:0.0.2 (via /tmp/xfs-22cbb318/dlx-22616/.yarn/__virtual__/@atls-figma-theme-font-sizes-generator-virtual-17e8ce7c31/4/home/operator/.yarn/berry/cache/@atls-figma-theme-font-sizes-generator-npm-0.0.2-82f8677b9b-10.zip/node_modules/@atls/figma-theme-font-sizes-generator/dist/)

Ancestor breaking the chain: @atls/figma-theme@virtual:062e44c5bb8a95907ff13535d1736cb0dd4fc59af574b300ca098f6edac71a3464eb3cd185b7d0e985469803e144392f5b8c8b207a6c1bdf38a3aa31de227455#npm:0.0.2


Require stack:
- /tmp/xfs-22cbb318/dlx-22616/.yarn/__virtual__/@atls-figma-theme-font-sizes-generator-virtual-17e8ce7c31/4/home/operator/.yarn/berry/cache/@atls-figma-theme-font-sizes-generator-npm-0.0.2-82f8677b9b-10.zip/node_modules/@atls/figma-theme-font-sizes-generator/dist/FigmaThemeFontSizesGenerator.js
- /tmp/xfs-22cbb318/dlx-22616/.yarn/__virtual__/@atls-figma-theme-font-sizes-generator-virtual-17e8ce7c31/4/home/operator/.yarn/berry/cache/@atls-figma-theme-font-sizes-generator-npm-0.0.2-82f8677b9b-10.zip/node_modules/@atls/figma-theme-font-sizes-generator/dist/index.js
- /tmp/xfs-22cbb318/dlx-22616/.yarn/__virtual__/@atls-figma-theme-virtual-7d78111ddc/4/home/operator/.yarn/berry/cache/@atls-figma-theme-npm-0.0.2-2228e7c4c0-10.zip/node_modules/@atls/figma-theme/dist/FigmaTheme.js
- /tmp/xfs-22cbb318/dlx-22616/.yarn/__virtual__/@atls-figma-theme-virtual-7d78111ddc/4/home/operator/.yarn/berry/cache/@atls-figma-theme-npm-0.0.2-2228e7c4c0-10.zip/node_modules/@atls/figma-theme/dist/index.js
- /home/operator/.yarn/berry/cache/@atls-figma-theme-cli-npm-0.0.2-062e44c5bb-10.zip/node_modules/@atls/figma-theme-cli/dist/run.js
- /home/operator/.yarn/berry/cache/@atls-figma-theme-cli-npm-0.0.2-062e44c5bb-10.zip/node_modules/@atls/figma-theme-cli/dist/index.js
    at require$$0.Module._resolveFilename (/tmp/xfs-22cbb318/dlx-22616/.pnp.cjs:6185:13)
    at Module._load (node:internal/modules/cjs/loader:984:27)
    at require$$0.Module._load (/tmp/xfs-22cbb318/dlx-22616/.pnp.cjs:6076:31)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/tmp/xfs-22cbb318/dlx-22616/.yarn/__virtual__/@atls-figma-theme-font-sizes-generator-virtual-17e8ce7c31/4/home/operator/.yarn/berry/cache/@atls-figma-theme-font-sizes-generator-npm-0.0.2-82f8677b9b-10.zip/node_modules/@atls/figma-theme-font-sizes-generator/dist/FigmaThemeFontSizesGenerator.js:4:40)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at require$$0.Module._extensions..js (/tmp/xfs-22cbb318/dlx-22616/.pnp.cjs:6228:33)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
```

**Comment by Nelfimov** [comment]
@effektivnayarabota1 

У тебя два варианта использования скрипта:
1. Установить пакет в твой `@ui/theme` и запускать через скрипт в виде:

```json
    "scripts": {
        "generate": "generate-theme"
    }
```

2. Склонировать репозиторий https://github.com/atls/figma локально, установить зависимости и запустить `generate-theme` скрипт из https://github.com/atls/figma/blob/master/theme/theme-cli/package.json

**Comment by effektivnayarabota1** [comment]
форс пушем не получается затолкнуть обновленную ветку (2 коммита слил в один)

```
[operator@archlinux 07_atls_team-management]$ git push origin feat/figma-theme -f
Username for 'https://github.com': effectivnayarabota1
Password for 'https://effectivnayarabota1@github.com': 
Enumerating objects: 46, done.
Counting objects: 100% (46/46), done.
Delta compression using up to 4 threads
Compressing objects: 100% (33/33), done.
Writing objects: 100% (36/36), 1.02 MiB | 17.20 MiB/s, done.
Total 36 (delta 6), reused 3 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (6/6), completed with 6 local objects.
remote: error: GH013: Repository rule violations found for refs/heads/feat/figma-theme.
remote: Review all repository rules at http://github.com/atls/team-management/rules?ref=refs%2Fheads%2Ffeat%2Ffigma-theme
remote: 
remote: - Cannot force-push to this branch
remote: 
To https://github.com/atls/team-management
 ! [remote rejected] feat/figma-theme -> feat/figma-theme (push declined due to repository rule violations)
error: failed to push some refs to 'https://github.com/atls/team-management'
[operator@archlinux 07_atls_team-management]$ git status
On branch feat/figma-theme
Your branch and 'origin/feat/figma-theme' have diverged,
and have 1 and 2 different commits each, respectively.
  (use "git pull" if you want to integrate the remote branch with yours)

nothing to commit, working tree clean
```

в настройках ветки нашел такой поинт:
![image](https://github.com/atls/team-management/assets/70315473/010750c5-e892-4372-b7f0-8cb95c5e0ed2)

ну а `git pull` соответсвенно подгружает ветку с гитхаба, где два коммита не слиты в один

**Comment by effektivnayarabota1** [comment]
щас обратил внимание, что обсуждение вопросов по этой теме идет и в `issues` и в `pull request`, это нормально? или лучше в одном направлении вести диалог по задаче?

**Comment by Nelfimov** [comment]
> щас обратил внимание, что обсуждение вопросов по этой теме идет и в `issues` и в `pull request`, это нормально? или лучше в одном направлении вести диалог по задаче?

Можно и там и там. Обычно в задаче обсуждаем конкретно задачу, в ПР - замечания к ПРу.

**Comment by effektivnayarabota1** [comment]
я провайдер написал, у меня все готово. хочу коммит поправить, дашь фидбек по этому вопросу?
https://github.com/atls/team-management/issues/1#issuecomment-2097888651

**Comment by Nelfimov** [comment]
Дал разрешение на форс пуши.
