### ISSUE TITLE
Сборка UI компонентов

### ISSUE THREAD

**Issue by Nelfimov** [atls/team-management#5]
### С чем связан запрос на фичу?

Необходимо подготовить UI компоненты, используемые в проекте.

### Расскажите как вы это себе видите

- [ ] проанализировать дизайн на наличие повторяемых компонентов
- [ ] собрать компоненты в `ui` слое
- [ ] использовать тему для стилизации

### Definition of done (критерий готовности)

`ui` слой собран, минимальный набор компонентов есть.

### Приложите пример реализаций

https://github.com/torin-asakura/dream-team/tree/master/ui

### Приложите материалы задачи

https://github.com/atls/hyperion

**Comment by Nelfimov** [comment]
@effektivnayarabota1 @bbulakh подключаю вас в эту задачу - имея готовые:
- энтрипоинт (скоро будет в мастере)
- тема

Надо собирать `ui` слой.

Порядок действий:
- [ ] оценить дизайн
- [ ] найти повторяющиеся компоненты - лэйауты, баттоны, инпуты, свитчеры
- [ ] найти в гиперионе аналог в `ui-parts`
- [ ] посмотреть как используется по другим проектам (drum-in, dream-team)

Предлагаю:
1. Собрать здесь общий список компонентов
2. Поделить между собой
3. Приступить к разработке в отдельных ветках и задачах

**Comment by bbulakh** [comment]
@Nelfimov @ssagg @effektivnayarabota1 

Ребята, вы уже коннектились как-то по этой задаче? Давайте соберемся обсудить и разделим всё. Я видел, что @ssagg уже начинал что-то делать

**Comment by effektivnayarabota1** [comment]
@Nelfimov @bbulakh 
начал докером заниматься. переключаться на эту задачу?

**Comment by Nelfimov** [comment]
@effektivnayarabota1 докер, как договорились.

@bbulakh @ssagg состыкуйтесь вместе, поделите компоненты.

**Comment by bbulakh** [comment]
@Nelfimov

Попробовал поставить тем же способом как в Dream Team. 
Получил такую ошибку. Я так понял, он ругается на то, что генератор не подтянул за собой Glob. Я поставил его вручную, но никак :

```
/usr/local/bin/node /Users/b_bulakh/Documents/ATLS/team-management/.yarn/releases/yarn-remote.cjs run build
/Users/b_bulakh/Documents/ATLS/team-management/.pnp.cjs:21345
      Error.captureStackTrace(firstError);
            ^

Error: glob-promise tried to access glob (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: glob
Required by: glob-promise@virtual:712d65b27bf35f9bab19e90dc1c9c73c9643838ff323e2bb0dd660af27322931e4e93d81af84818472eba1efa35bbd466ffc79fae3e3a45b0838b504a8a788c8#npm:5.0.1 (via /Users/b_bulakh/Documents/ATLS/team-management/.yarn/unplugged/glob-promise-virtual-31850d08b9/node_modules/glob-promise/lib/)

Ancestor breaking the chain: @atls-ui-generators/icons@npm:0.0.2


Require stack:
- /Users/b_bulakh/Documents/ATLS/team-management/.yarn/unplugged/glob-promise-virtual-31850d08b9/node_modules/glob-promise/lib/index.js
- /Users/b_bulakh/Documents/ATLS/team-management/.yarn/cache/@atls-ui-generators-icons-npm-0.0.2-712d65b27b-92da649cc2.zip/node_modules/@atls-ui-generators/icons/dist/svgr.js
- /Users/b_bulakh/Documents/ATLS/team-management/.yarn/cache/@atls-ui-generators-icons-npm-0.0.2-712d65b27b-92da649cc2.zip/node_modules/@atls-ui-generators/icons/dist/generator.js
    at require$$0.Module._resolveFilename (/Users/b_bulakh/Documents/ATLS/team-management/.pnp.cjs:21345:13)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at require$$0.Module._load (/Users/b_bulakh/Documents/ATLS/team-management/.pnp.cjs:21236:31)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/unplugged/glob-promise-virtual-31850d08b9/node_modules/glob-promise/lib/index.js:1:14)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at require$$0.Module._extensions..js (/Users/b_bulakh/Documents/ATLS/team-management/.pnp.cjs:21388:33)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at require$$0.Module._load (/Users/b_bulakh/Documents/ATLS/team-management/.pnp.cjs:21236:31)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/cache/@atls-ui-generators-icons-npm-0.0.2-712d65b27b-92da649cc2.zip/node_modules/@atls-ui-generators/icons/dist/svgr.js:35:40)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)

Node.js v20.13.0

Process finished with exit code 1
```

**Comment by Nelfimov** [comment]
Посмотри packageExtensions в .yarnrc

**Comment by effektivnayarabota1** [comment]
@bbulakh @ssagg 
дайте саппорт по компонентам

- [ ] - Badge - что это?
- [ ] - Dropdown - не могу найти в макете. компонент вижу на странице components, не вижу как в макете используется, посмотреть как выглядит развернутый.

@Nelfimov
- [ ] - Modal - модальное окно это же фрагмент странцы, не компонент? им позже будем заниматься?

**Comment by bbulakh** [comment]
@Nelfimov всё равно не получается с генератором

Вот последний коммит с драфтом:
https://github.com/atls/team-management/commit/cb4cfd4f15a6a947de0a40c87c610564b7af8cc5

Я пробовал разные команды, указывал пути к папкам в package.json. Всё равно ошибка: 

```
/usr/local/bin/node /Users/b_bulakh/Documents/ATLS/team-management/.yarn/releases/yarn-remote.cjs run build
/Users/b_bulakh/Documents/ATLS/team-management/.yarn/unplugged/glob-promise-virtual-78d57a6e49/node_modules/glob-promise/lib/index.js:5
    glob(pattern, options, (err, files) => err === null ? resolve(files) : reject(err))
    ^

TypeError: glob is not a function
    at /Users/b_bulakh/Documents/ATLS/team-management/.yarn/unplugged/glob-promise-virtual-78d57a6e49/node_modules/glob-promise/lib/index.js:5:5
    at new Promise (<anonymous>)
    at promise (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/unplugged/glob-promise-virtual-78d57a6e49/node_modules/glob-promise/lib/index.js:4:10)
    at build (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/__virtual__/@atls-ui-generators-icons-virtual-fee978e295/0/cache/@atls-ui-generators-icons-npm-0.0.2-712d65b27b-92da649cc2.zip/node_modules/@atls-ui-generators/icons/dist/svgr.js:83:52)
    at Command.<anonymous> (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/__virtual__/@atls-ui-generators-icons-virtual-fee978e295/0/cache/@atls-ui-generators-icons-npm-0.0.2-712d65b27b-92da649cc2.zip/node_modules/@atls-ui-generators/icons/dist/generator.js:35:28)
    at Command.listener [as _actionHandler] (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/cache/commander-npm-9.5.0-993b3f2434-41c49b3d0f.zip/node_modules/commander/lib/command.js:482:17)
    at /Users/b_bulakh/Documents/ATLS/team-management/.yarn/cache/commander-npm-9.5.0-993b3f2434-41c49b3d0f.zip/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/cache/commander-npm-9.5.0-993b3f2434-41c49b3d0f.zip/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/cache/commander-npm-9.5.0-993b3f2434-41c49b3d0f.zip/node_modules/commander/lib/command.js:1283:27)
    at Command.parse (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/cache/commander-npm-9.5.0-993b3f2434-41c49b3d0f.zip/node_modules/commander/lib/command.js:909:10)
    at Object.<anonymous> (/Users/b_bulakh/Documents/ATLS/team-management/.yarn/__virtual__/@atls-ui-generators-icons-virtual-fee978e295/0/cache/@atls-ui-generators-icons-npm-0.0.2-712d65b27b-92da649cc2.zip/node_modules/@atls-ui-generators/icons/dist/generator.js:38:9)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at require$$0.Module._extensions..js (/Users/b_bulakh/Documents/ATLS/team-management/.pnp.cjs:21712:33)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)

Node.js v20.13.0

Process finished with exit code 1
```

**Comment by bbulakh** [comment]
> @bbulakh @ssagg дайте саппорт по компонентам
> * [ ]  - Badge - что это?

Под бейджами имели в виду эти штуки 
<img width="51" alt="image" src="https://github.com/atls/team-management/assets/95144713/9b57e64b-073c-4726-9350-df137aa07932">

<img width="165" alt="image" src="https://github.com/atls/team-management/assets/95144713/6b5474df-8834-4ee8-b9bc-0cb5af0f95c7">

**Comment by Nelfimov** [comment]
> * [ ]  - Modal - модальное окно это же фрагмент странцы, не компонент? им позже будем заниматься?

Это компонент, в ui

**Comment by Nelfimov** [comment]
> @Nelfimov
> 
> Еще у меня есть компонент Checkbox, который я установил из Hyperion. Вот я пытаюсь вставить его в app/page, так же как с layout и пр. но он его не видит. Проблема в конфигах? Или надо делать вариант из ui-proto?
> 
> <img alt="image" width="793" src="https://private-user-images.githubusercontent.com/95144713/330069118-742cf285-b3d5-4e10-be4b-fd89d3ef7329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDY5MzEsIm5iZiI6MTcxNTYwNjYzMSwicGF0aCI6Ii85NTE0NDcxMy8zMzAwNjkxMTgtNzQyY2YyODUtYjNkNS00ZTEwLWJlNGItZmQ4OWQzZWY3MzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEzMjM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhN2Q2YjIxZWNkYTNlOTUzOWZlMTMzNjVkZjBhMzA5NDBlM2UwYzkyYWZhMmU2NDAyODI0M2EzNzM0ZDYzNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dp1x7-0WMKF7auxFGfANgmmdA7lYdHzcQjLPm7lL96Q">

1. Ты пишешь в чужом предложении без ссылки на свою ветку и логов, поэтому оцениваю только так
2. Проверь есть ли у тебя экспорт Box из Checkbox

**Comment by ssagg** [comment]
@Nelfimov @effektivnayarabota1 @bbulakh 
У меня вот так сейчас все выглядит. 
![Screenshot from 2024-05-13 10-27-36](https://github.com/atls/team-management/assets/104500533/399d8ec0-6916-4962-bbdb-e704172bf048)

**Comment by effektivnayarabota1** [comment]
@ssagg 
пока два компонента. сейчас буду свич с иконками делать
ты писал бейдж есть? на скрине нет его
![image](https://github.com/atls/team-management/assets/70315473/7526e5d3-68b0-476d-98c4-f82732d6bf71)

**Comment by Nelfimov** [comment]
@bbulakh @effektivnayarabota1  сделайте себе отдельные задачи и пишите там.

@bbulakh в моем коммите 505477c693b298a38cd350902f10ae017db1b9c7 фикс генератора. посмотри внимательно на yarnrc.yml

**Comment by Nelfimov** [comment]
@ssagg @bbulakh @effektivnayarabota1 задача не была привязана к ПРу, поэтому не закрылась автоматом с закрытием ПР
